"""embedding_cache

Revision ID: 630dc9fee8e6
Revises: 72b61c031c41
Create Date: 2026-09-30 13:27:33.582453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '630dc9fee8e6'
down_revision: Union[str, Sequence[str], None] = '72b61c031c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding_version', sa.String(length=128), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('dimension > 0'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text_hash', 'embedding_version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('embedding_cache')
    # ### end Alembic commands ###
