"""initial_schema

Revision ID: 72b61c031c41
Revises:
Create Date: 2026-09-30 13:19:56.988842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72b61c031c41'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_question',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_text', sa.Text(), nullable=False),
    sa.Column('primary_topic_id', sa.String(length=128), nullable=False),
    sa.Column('taxonomy_version', sa.String(length=64), nullable=False),
    sa.Column('question_type', sa.String(length=32), nullable=False),
    sa.Column('lifecycle', sa.String(length=16), nullable=False),
    sa.Column('redirect_to_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['redirect_to_id'], ['canonical_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corpus_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_revision', sa.Integer(), nullable=False),
    sa.Column('activation_manifest', sa.JSON(), nullable=False),
    sa.Column('canonical_snapshot', sa.JSON(), nullable=False),
    sa.Column('versions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corpus_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_revision', sa.Integer(), nullable=False),
    sa.Column('indexed_revision', sa.Integer(), nullable=False),
    sa.Column('taxonomy_version', sa.String(length=64), nullable=False),
    sa.Column('canonical_revision', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idempotency_receipt',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('namespace', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace', 'actor_id', 'idempotency_key')
    )
    op.create_table('index_sync_task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('corpus_revision', sa.Integer(), nullable=False),
    sa.Column('affected_canonical_ids', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corpus_revision')
    )
    op.create_table('pipeline_run',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_version', sa.String(length=64), nullable=False),
    sa.Column('extractor_version', sa.String(length=64), nullable=False),
    sa.Column('taxonomy_version', sa.String(length=64), nullable=False),
    sa.Column('embedding_version', sa.String(length=64), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_documents', sa.Integer(), nullable=False),
    sa.Column('processed_questions', sa.Integer(), nullable=False),
    sa.Column('failed_documents', sa.Integer(), nullable=False),
    sa.Column('skipped_documents', sa.Integer(), nullable=False),
    sa.Column('excluded_documents', sa.Integer(), nullable=False),
    sa.Column('needs_review_documents', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_document',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_identity', sa.String(length=512), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('original_relative_path', sa.Text(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('active_build_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['active_build_id'], ['document_build.id'], name='fk_source_active_build', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_identity')
    )
    op.create_table('stage_artifact',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('output_hash', sa.String(length=64), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('artifact_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    op.create_table('user_revision',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('state_revision', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('review_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('canonical_question_id', sa.String(length=36), nullable=True),
    sa.Column('raw_question', sa.Text(), nullable=True),
    sa.Column('requested_status', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('item_index', sa.Integer(), nullable=False),
    sa.Column('resolution_status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['canonical_question_id'], ['canonical_question.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', 'item_index')
    )
    op.create_table('source_revision',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=False),
    sa.Column('raw_file_hash', sa.String(length=64), nullable=False),
    sa.Column('snapshot_path', sa.Text(), nullable=False),
    sa.Column('raw_file_path', sa.Text(), nullable=False),
    sa.Column('decoded_text_hash', sa.String(length=64), nullable=True),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_document_id', 'raw_file_hash')
    )
    op.create_index(op.f('ix_source_revision_source_document_id'), 'source_revision', ['source_document_id'], unique=False)
    op.create_table('user_question_state',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('canonical_question_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('binding_status', sa.String(length=16), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('last_score', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('review_count >= 0'),
    sa.ForeignKeyConstraint(['canonical_question_id'], ['canonical_question.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'canonical_question_id')
    )
    op.create_table('document_build',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_revision_id', sa.String(length=36), nullable=False),
    sa.Column('processing_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('document_kind', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('processing_state', sa.String(length=20), nullable=False),
    sa.Column('publication_state', sa.String(length=20), nullable=False),
    sa.Column('exclusion_reason', sa.Text(), nullable=True),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_revision_id'], ['source_revision.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_revision_id', 'processing_fingerprint')
    )
    op.create_index(op.f('ix_document_build_source_revision_id'), 'document_build', ['source_revision_id'], unique=False)
    op.create_table('interview',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('build_id', sa.String(length=36), nullable=False),
    sa.Column('session_key', sa.String(length=128), nullable=False),
    sa.Column('session_order', sa.Integer(), nullable=False),
    sa.Column('session_kind', sa.String(length=32), nullable=False),
    sa.Column('company_raw', sa.Text(), nullable=True),
    sa.Column('company_normalized', sa.String(length=128), nullable=True),
    sa.Column('department_raw', sa.Text(), nullable=True),
    sa.Column('position_raw', sa.Text(), nullable=True),
    sa.Column('position_normalized', sa.String(length=128), nullable=True),
    sa.Column('job_family', sa.String(length=32), nullable=True),
    sa.Column('language_tags', sa.JSON(), nullable=False),
    sa.Column('round_raw', sa.Text(), nullable=True),
    sa.Column('round', sa.String(length=32), nullable=True),
    sa.Column('interview_date', sa.Date(), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('date_evidence', sa.JSON(), nullable=False),
    sa.Column('metadata_evidence', sa.JSON(), nullable=False),
    sa.Column('analytics_eligible', sa.Boolean(), nullable=False),
    sa.Column('extractor_version', sa.String(length=64), nullable=False),
    sa.Column('taxonomy_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['document_build.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('build_id', 'session_key')
    )
    op.create_index(op.f('ix_interview_build_id'), 'interview', ['build_id'], unique=False)
    op.create_index(op.f('ix_interview_company_normalized'), 'interview', ['company_normalized'], unique=False)
    op.create_index(op.f('ix_interview_interview_date'), 'interview', ['interview_date'], unique=False)
    op.create_index(op.f('ix_interview_job_family'), 'interview', ['job_family'], unique=False)
    op.create_index(op.f('ix_interview_publish_date'), 'interview', ['publish_date'], unique=False)
    op.create_index(op.f('ix_interview_round'), 'interview', ['round'], unique=False)
    op.create_table('pipeline_task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('revision_id', sa.String(length=36), nullable=True),
    sa.Column('build_id', sa.String(length=36), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('task_key', sa.String(length=64), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['stage_artifact.id'], ),
    sa.ForeignKeyConstraint(['build_id'], ['document_build.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['source_revision.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_run.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'task_key')
    )
    op.create_table('model_call',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('operation_type', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('model_revision', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('usage_source', sa.String(length=16), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_run.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['pipeline_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_occurrence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('interview_id', sa.String(length=36), nullable=False),
    sa.Column('canonical_question_id', sa.String(length=36), nullable=True),
    sa.Column('raw_question', sa.Text(), nullable=False),
    sa.Column('normalized_question', sa.Text(), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('context_before', sa.Text(), nullable=True),
    sa.Column('context_after', sa.Text(), nullable=True),
    sa.Column('source_spans', sa.JSON(), nullable=False),
    sa.Column('topic_id', sa.String(length=128), nullable=False),
    sa.Column('taxonomy_version', sa.String(length=64), nullable=False),
    sa.Column('question_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_origin', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1'),
    sa.ForeignKeyConstraint(['canonical_question_id'], ['canonical_question.id'], ),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id', 'question_order')
    )
    op.create_index(op.f('ix_question_occurrence_canonical_question_id'), 'question_occurrence', ['canonical_question_id'], unique=False)
    op.create_index(op.f('ix_question_occurrence_interview_id'), 'question_occurrence', ['interview_id'], unique=False)
    op.create_index(op.f('ix_question_occurrence_question_type'), 'question_occurrence', ['question_type'], unique=False)
    op.create_index(op.f('ix_question_occurrence_topic_id'), 'question_occurrence', ['topic_id'], unique=False)
    op.create_table('algorithm_match',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('occurrence_id', sa.String(length=36), nullable=False),
    sa.Column('coding_kind', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('problem_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('match_status', sa.String(length=16), nullable=False),
    sa.Column('match_basis', sa.String(length=32), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('catalog_version', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['occurrence_id'], ['question_occurrence.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('occurrence_id', 'platform', 'problem_id')
    )
    op.create_table('canonical_assignment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('occurrence_id', sa.String(length=36), nullable=False),
    sa.Column('canonical_question_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('candidate_ids', sa.JSON(), nullable=False),
    sa.Column('judge_version', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('valid_from_revision', sa.Integer(), nullable=False),
    sa.Column('valid_to_revision', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_question_id'], ['canonical_question.id'], ),
    sa.ForeignKeyConstraint(['occurrence_id'], ['question_occurrence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_assignment_occurrence_id'), 'canonical_assignment', ['occurrence_id'], unique=False)
    op.create_index('uq_current_canonical_assignment', 'canonical_assignment', ['occurrence_id'], unique=True, sqlite_where=sa.text('valid_to_revision IS NULL'), postgresql_where=sa.text('valid_to_revision IS NULL'))
    op.create_table('question_relation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.Column('source_occurrence_id', sa.String(length=36), nullable=True),
    sa.Column('target_occurrence_id', sa.String(length=36), nullable=True),
    sa.Column('source_canonical_id', sa.String(length=36), nullable=True),
    sa.Column('target_canonical_id', sa.String(length=36), nullable=True),
    sa.Column('source_interview_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_spans', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('producer_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(relation_type = 'OBSERVED_FOLLOWUP' AND source_occurrence_id IS NOT NULL AND target_occurrence_id IS NOT NULL AND source_canonical_id IS NULL AND target_canonical_id IS NULL) OR (relation_type IN ('RELATED','SIMILAR') AND source_occurrence_id IS NULL AND target_occurrence_id IS NULL AND source_canonical_id IS NOT NULL AND target_canonical_id IS NOT NULL)", name='relation_endpoint_type'),
    sa.ForeignKeyConstraint(['source_canonical_id'], ['canonical_question.id'], ),
    sa.ForeignKeyConstraint(['source_interview_id'], ['interview.id'], ),
    sa.ForeignKeyConstraint(['source_occurrence_id'], ['question_occurrence.id'], ),
    sa.ForeignKeyConstraint(['target_canonical_id'], ['canonical_question.id'], ),
    sa.ForeignKeyConstraint(['target_occurrence_id'], ['question_occurrence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_relation')
    op.drop_index('uq_current_canonical_assignment', table_name='canonical_assignment', sqlite_where=sa.text('valid_to_revision IS NULL'), postgresql_where=sa.text('valid_to_revision IS NULL'))
    op.drop_index(op.f('ix_canonical_assignment_occurrence_id'), table_name='canonical_assignment')
    op.drop_table('canonical_assignment')
    op.drop_table('algorithm_match')
    op.drop_index(op.f('ix_question_occurrence_topic_id'), table_name='question_occurrence')
    op.drop_index(op.f('ix_question_occurrence_question_type'), table_name='question_occurrence')
    op.drop_index(op.f('ix_question_occurrence_interview_id'), table_name='question_occurrence')
    op.drop_index(op.f('ix_question_occurrence_canonical_question_id'), table_name='question_occurrence')
    op.drop_table('question_occurrence')
    op.drop_table('model_call')
    op.drop_table('pipeline_task')
    op.drop_index(op.f('ix_interview_round'), table_name='interview')
    op.drop_index(op.f('ix_interview_publish_date'), table_name='interview')
    op.drop_index(op.f('ix_interview_job_family'), table_name='interview')
    op.drop_index(op.f('ix_interview_interview_date'), table_name='interview')
    op.drop_index(op.f('ix_interview_company_normalized'), table_name='interview')
    op.drop_index(op.f('ix_interview_build_id'), table_name='interview')
    op.drop_table('interview')
    op.drop_index(op.f('ix_document_build_source_revision_id'), table_name='document_build')
    op.drop_table('document_build')
    op.drop_table('user_question_state')
    op.drop_index(op.f('ix_source_revision_source_document_id'), table_name='source_revision')
    op.drop_table('source_revision')
    op.drop_table('review_event')
    op.drop_table('user_revision')
    op.drop_table('stage_artifact')
    op.drop_table('source_document')
    op.drop_table('pipeline_run')
    op.drop_table('index_sync_task')
    op.drop_table('idempotency_receipt')
    op.drop_table('corpus_state')
    op.drop_table('corpus_revision')
    op.drop_table('canonical_question')
    # ### end Alembic commands ###
